#pragma once

#ifndef CONFIG_GPIO_BJM1_BUTTON1_SINK
#define CONFIG_GPIO_BJM1_BUTTON1_SINK 13
#endif
#define CONFIG_BUTTON1_INITIAL_STATE 0
#define CONFIG_BUTTON1_LATCHING 1
#define CONFIG_BUTTON1_INVERTED 0

