#pragma once

#ifndef CONFIG_SERIAL_WAIT
#define CONFIG_SERIAL_WAIT 1
#endif

#ifndef CONFIG_GPIO_LEFT_BLINKER
#define CONFIG_GPIO_LEFT_BLINKER 0
#endif

#ifndef CONFIG_GPIO_RIGHT_BLINKER
#define CONFIG_GPIO_RIGHT_BLINKER 0
#endif

#ifndef CONFIG_GPIO_CENTER_STOP_LIGHT
#define CONFIG_GPIO_CENTER_STOP_LIGHT 0
#endif

#define CONFIG_STOP_LIGHT_GPIO_INVERTED 0
#define CONFIG_LEFT_BLINKER_GPIO_INVERTED 0
#define CONFIG_RIGHT_BLINKER_GPIO_INVERTED 0
